name: "fofanaabou's Action in Action"
description: 'Greets someone and returns always 42.'
branding:
  icon: 'sunrise'
  color: yellow
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'
outputs:
  answer:
    description: 'The answer to everything (always 42)'
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}